apiVersion: v1
kind: Pod
metadata:
  name: kube-sherlock
spec:
  serviceAccountName: kube-sherlock
  containers:
    - name: kube-sherlock
      image: cmendibl3/kube-sherlock:0.1
      volumeMounts:
      - name: config-volume
        mountPath: /app/config.yaml
        subPath: config.yaml
  volumes:
    - name: config-volume
      configMap:
        name: sherlock-config
  restartPolicy: Never

 apiVersion: v1
 kind: ConfigMap
 metadata:
  name: sherlock-config
  namespace: default
  data:
  config.yaml: |
    namespaces:
      - default
    labels:
      - "app"
      - "owner" 
